# Exercise 03.04 (Assignment #01) — 3D Linear Transformations

In [2]:
import numpy as np

## Shape: a square pyramid

4 base corners forming a flat square (z=0), plus 1 apex centered above the base and raised up. Each row is one 3D point (x, y, z).

In [ ]:
P = np.array([
    [0, 0, 0],       # middle
    [1, 0, 0],       # base corner
    [1, 1, 0],       # base corner
    [0, 1, 0],       # base corner
    [0.5, 0.5, 1],   # apex, centered above the base, raised up
])

print("pyramid points:")
print(P)

Original pyramid points:
[[0.  0.  0. ]
 [1.  0.  0. ]
 [1.  1.  0. ]
 [0.  1.  0. ]
 [0.5 0.5 1. ]]


<img src="../Assets/Exercise 03.04 /SquarePyr.png" alt="Original pyramid" width="300">

## Transformation matrices

- **Scaling** — doubles every coordinate.
- **Rotation** — spins the shape 90° around the z-axis (leaves z untouched).
- **Shear** — skews the shape by dragging y along with x.

In [ ]:
T_scale = np.array([[2, 0, 0],
                    [0, 2, 0],
                    [0, 0, 2]])

T_rotate = np.array([[0, -1, 0],
                     [1,  0, 0],
                     [0,  0, 1]])

T_shear = np.array([[1, 0, 0],
                    [1, 1, 0],
                    [0, 0, 1]])

print("T_scale =\n", T_scale)
print("T_rotate =\n", T_rotate)
print("T_shear =\n", T_shear)

T_scale =
 [[2 0 0]
 [0 2 0]
 [0 0 2]]
T_rotate =
 [[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]
T_shear =
 [[1 0 0]
 [1 1 0]
 [0 0 1]]


## Applying the transformation

Each `T` is 3x3 because it transforms a single 3D point (3 in, 3 out) and not the whole `(5,3)` table at once. The same 3x3 matrix gets reused once per row of `P`.

`T @ point` does 3 dot products, one per row of `T`, against the point. Each dot product becomes one coordinate of the new point:

For point 2 with row `(1, 0, 0)`, using `T_scale`:
- **Row 1** `[2,0,0]` . `(1,0,0)` = `(2×1) + (0×0) + (0×0)` = `2` -> new x
- **Row 2** `[0,2,0]` . `(1,0,0)` = `(0×1) + (2×0) + (0×0)` = `0` -> new y
- **Row 3** `[0,0,2]` . `(1,0,0)` = `(0×1) + (0×0) + (2×0)` = `0` -> new z

Stacking those three results gives the new point: `(2, 0, 0)`.

Since every transformation is applied the same way, one helper function works for any `T`.

In [ ]:
def apply_transform(T, points):
    return np.array([T @ point for point in points])

scaled = apply_transform(T_scale, P)
rotated = apply_transform(T_rotate, P)
sheared = apply_transform(T_shear, P)

print("Scaled points (x2):\n", scaled)
print("\nRotated points (90 deg around z):\n", rotated)
print("\nSheared points:\n", sheared)

## Results

<div style="display:flex; gap:16px; align-items:flex-start;">
  <div>
    <p><strong>Scaled</strong></p>
    <img src="../Assets/Exercise 03.04 /SquarePyr_scaled.png" alt="Scaled pyramid" width="220">
  </div>
  <div>
    <p><strong>Red = original, blue = rotated.</strong></p>
    <img src="../Assets/Exercise 03.04 /SquarePyr_rotated.png" alt="Original (red) vs rotated (blue) pyramid" width="220">
  </div>
  <div>
    <p><strong>Red = original, blue = sheared.</strong></p>
    <img src="../Assets/Exercise 03.04 /SquarePyr_Shear.png" alt="Original (red) vs sheared (blue) pyramid" width="220">
  </div>
</div>

## Interpretation

- **Scaling** stretched every point uniformly by 2x — same shape, just bigger, since the diagonal matrix scales each axis independently by the same factor.
- **Rotation** spun the base 90° around the z-axis while leaving height untouched. It's a *rigid* transformation where size and shape are preserved, only orientation changes.
- **Shearing** was the only one that actually distorted the shape: y-values got dragged along by x (`row 2 = [1,1,0]`), so `(0,1,0)` didn't move but `(1,1,0)` shifted all the way to `(1,2,0)`, skewing the angles.
- **Combining:** since each is just a matrix, chaining transformations is matrix multiplication (`T2 @ (T1 @ point) = (T2 @ T1) @ point`). Order matters — just like `A @ T` vs `T @ A` gave different results back in 03.03 — so rotate-then-shear ≠ shear-then-rotate.